### PR TITLE
feat: Support ESLint 7.x

### LINKED ISSUE #189: Support ESLint 7.x
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

(dev)Dependencies should be compatible with ESLint 7 too before we can merge this one:

- [x] [`eslint-plugin-eslint-plugin`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/94)
  - [x]  [PR 1](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/92)
  - [x] [PR 2](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/95)
  - [x]  [Released](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/CHANGELOG.md#v300-2021-04-08)
- [x] [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest/issues/568)
  - [x]  [PR](https://github.com/jest-community/eslint-plugin-jest/pull/572)
  - [x]  Released
- [ ] [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node/issues/223)
  - [ ] [PR](https://github.com/mysticatea/eslint-plugin-node/pull/224)
  - [ ]  Released
- [x] [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier/issues/292)
  - [x]  [PR](https://github.com/prettier/eslint-plugin-prettier/issues/291)
  - [x]  Released
- [x] [`jest-runner-eslint`](https://github.com/jest-community/jest-runner-eslint/issues/91)
  - [x]  [PR](https://github.com/jest-community/jest-runner-eslint/pull/92)
  - [x]  [Release](https://github.com/jest-community/jest-runner-eslint/compare/v0.9.0...v0.10.0)

---

BREAKING CHANGE: Requires Node@^10.12.x || 12.x
BREAKING CHANGE: Requires ESLint@^7.x

Closes #189

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this @MichaelDeBoey! 

Hi @xjamundx 👋👋👋

**Comment by MichaelDeBoey** [comment]
@kentcdodds We still have to wait for `eslint-plugin-eslint-plugin` (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/95), `eslint-plugin-node` (https://github.com/mysticatea/eslint-plugin-node/pull/224) & `jest-runner-eslint` (https://github.com/jest-community/jest-runner-eslint/pull/92) before we can merge this one

**Comment by xjamundx** [comment]
Let me know when this is ready and I can review. I've mostly abandoned this project, but I can get this in.

**Comment by kentcdodds** [comment]
Thanks @xjamundx!

With almost 500k projects relying on this module, perhaps it would be good to find another maintainer?

image

**Comment by xjamundx** [comment]
@kentcdodds 😱

**Comment by xjamundx** [comment]
@MichaelDeBoey feel free to remove any dev deps causing issues. We'll probably publish this as a breaking change anyhow.

**Comment by MichaelDeBoey** [comment]
@xjamundx We still have to wait for `eslint-plugin-eslint-plugin` (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/95) & `eslint-plugin-node` (https://github.com/mysticatea/eslint-plugin-node/pull/224), which are both waiting for `eslint-utils` (https://github.com/mysticatea/eslint-utils/pull/7) before we can merge this one

**Comment by MichaelDeBoey** [comment]
@xjamundx This one can be merged if you want to

**Comment by MichaelDeBoey** [comment]
@xjamundx This one can be merged if you want to

**Comment by xjamundx** [comment]
Publish as a breaking change?

**Comment by MichaelDeBoey** [comment]
@xjamundx This is indeed a breaking change

**Comment by xjamundx** [comment]
`+ eslint-plugin-promise@5.0.0`

**Pull request merged**
