### PR TITLE
Allow throw in always-return rule

### PR DESCRIPTION
**Pull request by dbrockman**
Throwing an error is a valid way of terminating the function passed to `then` and will result in a rejected promise.

If this PR is merged it will allow something like this:

```js
function isUserLoggedIn (username) {
  return getUserByName(username).then(user => {
    if (user) {
      return user.isLoggedOut();
    }
    throw new Error('user not found');
  });
}
```

### CODE REVIEW

**Comment by xjamundx** [comment]
Let me think about this a bit, thanks!

**Comment by xjamundx** [comment]
I think it will be okay if you can update the readme

**Comment by jeffdolle-sge** [comment]
I encountered this issue too. IMO this is a very serious problem, since I am using https://github.com/github/fetch and throw seems to be the recommended way of rejecting the promise.

Is the hold up just the readme? If you'd like, I can open a new PR with these changes and an updated readme, or if you'd prefer, just an updated readme (so you merge both PRs separately).

**Comment by xjamundx** [comment]
merging

**Pull request merged**
