### PR TITLE
Meta type

### PR DESCRIPTION
**Pull request by brettz9**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [x] Other, please explain: Adds metadata

**What changes did you make? (Give an overview)**

- Enhancement: Add `meta.type` to all rules

Can use `eslint --fix-type` with meta.type (see https://eslint.org/docs/user-guide/command-line-interface#fix-type )

(I'm also working on an eslint badge formatter which allows categorizing rule violations by `meta.type` (i.e., problem, layout, or suggestion), so having this fixed would allow it to be properly categorized.)

### CODE REVIEW

**Comment by brettz9** [comment]
Any chance y'all can take a look? Thanks...

**Comment by xjamundx** [comment]
Will try to look this weekend or on Monday. Appreciate it

**Comment by brettz9** [comment]
What, no firm *promises* from the promise plugin? ;-)  JK of course... Thanks!

**Comment by xjamundx** [comment]
I'm basically fine with this change, but not really in love with the formatting change (specifically adding trailing commas). If you want to introduce another PR where you bring in prettier that would be fine, but otherwise I'd prefer if you could remove that change and then I'll be fine with merging.

**Comment by brettz9** [comment]
I guess you mean I could add a separate PR to *update* Prettier (which starts requiring trailing commas) along with the corresponding linting changes?

**Comment by brettz9** [comment]
I've amended to stop depending on my other PRs #183 and #184, where #184 added the linting.

**Pull request merged**
