### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by brettz9**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [x] Other, please explain:

Testing coverage

**What changes did you make? (Give an overview)**

Builds on #195 (so that there would be a passing tests/linting baseline)

- Testing: Check coverage
- Testing: Set thresholds for coverage (100%)
- Testing: Get to 100% coverage
- Refactoring: Internally rename `isCallingBack` to `isCallback` as per file name and usage

In the process, this PR includes refactoring to remove dead code (and thereby avoid the need for `istanbul ignore`):
- removed code block from `always-return` which is not necessary given that "good" return/throw statements cannot occur within shortcut syntax (which expect expressions)

If you prefer that all of the code be refactored to avoid `istanbul ignore`, I can do so, but I think the other code was more reasonable as a sanity guard (i.e., in case the code were ever refactored, those checks may be necessary).

### CODE REVIEW

**Comment by brettz9** [comment]
I guess I need to wait until #195 may be merged into `development`, so I can refactor on top of that.

**Comment by brettz9** [comment]
I've rebased this as well as #197 and #198 on latest `development`.

**Comment by brettz9** [comment]
Rebased. Note that this also currently adds changes of #184 / #188 (added to `master`)--IIRC, necessary for getting to full coverage and/or satisfying the linter. Also updates some devDeps. and the lock file (using npm@7 format, requiring devs working on the project to use npm@7)

**Comment by xjamundx** [comment]
I personally don't care about 100% test coverage, but if we have it, let's try to keep it :D

**Comment by brettz9** [comment]
Cool--Appreciate the flexibility! FWIW, besides giving some assurances that edge cases have been considered and are working as expected, I find another advantage is ensuring self-documentation for others about what will happen under those edge case conditions.

**Pull request merged**
