### PR TITLE
bumps deps; use ESLint 3 rule format

### PR DESCRIPTION
**Pull request by jokeyrhyme**
- use ESLint 3 rule format: http://eslint.org/blog/2016/07/eslint-new-rule-format

- specify ESLint ^2.10 or ^3 as a peerDependency to help `npm` users identify compatibility issues

- ~~specify Node.js 4 as the minimum: http://eslint.org/docs/user-guide/migrating-to-3.0.0#dropping-support-for-nodejs--4~~

### CODE REVIEW

**Comment by feross** [comment]
I would make the following changes:

- Remove the `.editorconfig` changes (send a separate PR for that if you want, so it can be discussed separately from these changes)

- Node v4 and eslint 3 peer dependency changes: since folks can still use this config with eslint 2.10.0 and newer, there is no need to restrict these version ranges so much. I would set the eslint peer dependency to `>=2.10.0` and remove the node version restriction.

- No need for arrow functions -- this package can still support node < 4 and eslint 2 if @xjamundx is interested in doing that.

**Comment by jokeyrhyme** [comment]
@feross done!

@xjamundx any thing else I should do to get this ready to merge?

**Comment by xjamundx** [comment]
Looks good to me, will try to get to this later tonight!

**Comment by xjamundx** [comment]
```
+ eslint-plugin-promise@2.0.0
```

**Comment by feross** [comment]
🎉

**Pull request merged**
