### PR TITLE
prefer-await-to-then should flag promise.catch/finally as well

### PR DESCRIPTION
**Pull request by jp7837**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New rule
- [x] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Other, please explain:

**What changes did you make? (Give an overview)**
Flag `catch()` and `finally()` usages in the `prefer-await-to-then` rule

### CODE REVIEW

**Comment by jp7837** [comment]
Fixes #187

**Comment by jp7837** [comment]
@xjamundx thoughts on this one?

**Comment by xjamundx** [comment]
Yeah seems fine.

**Comment by xjamundx** [comment]
Actually.....Let me take this back (sorry).

`.catch()` really is an error handling mechanism and not really the same as `await`. 

For example I prefer `.catch()` to `try/catch`

**Comment by jp7837** [comment]
@xjamundx yeah, that makes sense, it is cleaner to use `catch()` in that case.  I just used the below instead.  And I was actually just applying it to Jest code in combination with [no-try-expect](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-try-expect.md) to get more reliable and cleaner error assertions.

```js
"no-restricted-properties": [
	"error",
	{
		property: "catch",
		message: "Use async/await instead of catch"
	},
	{
		property: "finally",
		message: "Use async/await instead of finally"
	},
	{
		property: "then",
		message: "Use async/await instead of then"
	},
]
```

**Pull request merged**
